# Generated by Django 4.0.4 on 2022-05-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_remove_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.CharField(db_collation='utf8_general_ci', max_length=255, null=True),
        ),
    ]
