# Generated by Django 4.0.4 on 2022-05-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_post_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_url',
        ),
    ]
