# Generated by Django 4.0.4 on 2022-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/%Y/%m'),
        ),
    ]
