# Generated by Django 4.0.4 on 2022-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_alter_postdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
