# Generated by Django 4.0.4 on 2022-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post_id',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='socialapp.post'),
        ),
    ]
